CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    password TEXT,
    username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS playlists (
    id INTEGER PRIMARY KEY,
    name TEXT,
    user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS songs (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    playlist_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY(playlist_id) REFERENCES playlists(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY(user_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    genre TEXT NOT NULL
);